language: php

sudo: false

php:
 - 5.5
 - 5.6
 - 7.0
 - 7.1
 - 7.2

before_script:
 - git config --global user.email "you@example.com"
 - git config --global user.name "Your Name"
# - git checkout -b master
 - phpenv config-add travis.php.ini

script:
 - phpunit --verbose --colors --coverage-clover=coverage.clover phpcf-src/test/PhpCfTest.php
# - phpunit phpcf-src/test/PhpCfFunctional.php --debug

after_success:
 - wget https://scrutinizer-ci.com/ocular.phar
 - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
